nav_msgs/Path init_path                 # Generator
std_msgs/Int8 generator_mode            # Generator
std_msgs/Float32[] max_vel_percentage   # Generator
std_msgs/Int8 follower_mode
std_msgs/Float32 look_ahead
std_msgs/Float32 cruising_speed
---
nav_msgs/Path generated_path