nav_msgs/Path generated_path
std_msgs/Int8 follower_mode
std_msgs/Float32 look_ahead
std_msgs/Float32 cruising_speed
std_msgs/Float32 max_velocity
std_msgs/Float32[] generated_max_vel_percentage
---
std_msgs/Bool ok