nav_msgs/Path init_path
std_msgs/Int8 generator_mode
std_msgs/Float32[] max_vel_percentage
---
nav_msgs/Path generated_path
std_msgs/Float32 max_velocity
std_msgs/Float32[] generated_max_vel_percentage