nav_msgs/Path init_path
nav_msgs/Path current_path
nav_msgs/Path generated_path
geometry_msgs/TwistStamped current_vel
geometry_msgs/TwistStamped desired_vel
std_msgs/Float32[] init_times
std_msgs/Float32[] generated_times
---